:toc:
:toc-placement!:
:toclevels: 4
:toclevels: 1

= Apartments
:gitHubUserName: oliviercailloux
:groupId: io.github.{gitHubUserName}
:artifactId: apartments
:repository: Apartments
A Java project developed by students during the https://github.com/oliviercailloux/java-course[Java course] taught at Université Paris-Dauphine (in https://dauphine.psl.eu/formations/licences/informatique-des-organisations/l3-methodes-informatiques-appliquees-pour-la-gestion-des-entreprises[L3 MIAGE Alternance]).
image:https://github.com/{gitHubUserName}/{repository}/workflows/Java%20CI%20with%20Maven/badge.svg?branch=master["Build Status", link="https://github.com/{gitHubUserName}/{repository}/actions"]

toc::[]

== Itérations UML 2021

=== Iteration 1 UML

[IMPORTANT]
====
Deadline : **Febrary the 14th,** 2021
This file only explains the distribution of work between the different teams and indicates their realization.
====
NOTE: The first iteration does not reflect the countless hours we spent understanding the projet. We aim, in the future, to create a global doc in order to explain the main functionalities and how to manage it.

==== Ewen MARGUET & Seif BOUGUERRA

 * SM/PO for this iteration.
 * Have split the work between the two groups.
 * Organized meetings throughout the week to have a better understanding of the projet.
 * Made sure everybody was on board and respected the deadline.

==== Maïrame NDIAYE & Abla MIKOU

 * Modifying the global_UC Diagram: Deleting unrelated information, and changing the main interaction with Tenant.
 * Adding a generalized interaction "Manage apartments" with two sub-divisions.
 * Modifying CreateApartmentsUC: Changing the whole diagram. Renaming it ManageApartments, with two main use cases "Modify Apartment" and "Create Apartment". Then, adding "Modify fields" and interactions.

==== Samy MEGUENI & Stellan WEA

 * Modifying AskOpinionForUtilityUC: Merge different parameters, modify title to a more efficient name. Transform "extends" in "uses"
 * Create SetPreferencesUC: Adding different interaction with the main user (Tenant)

=== Itération 2 UML

[IMPORTANT]
====
Deadline : **March the 14th,** 2021
This file only explains the distribution of work between the different teams and indicates their realization.
====

==== Maïrame NDIAYE & Samy MEGUENI

* SM/PO for this iteration.
* Have split the work between the two groups.
* Organized meetings throughout the week to have a better understanding of the projet.
* Made sure everybody was on board and respected the deadline.

==== Ewen MARGUET & Abla MIKOU

* Creating ID_valuefonction : Creating an Interaction Diagram of valuefunction. As long as the user wants to put criterias, we compute again the appartments' score and show the best appartments corresponding to this criterias. **(prerequisites : correcting conceptual errors in model)**
* Correcting conceptual errors in model. **(mandatory first step)**
* Update GlobalUC : adding the possibility to show statistics and to compare 2 apartments chosen by the user, deleting unrelated information, and changing the main interaction with Tenant. **(prerequisites : correcting conceptual errors in model)**

==== Seif BOUGUERRA & Stellan WEA

* Creating DC_DistanceApartment : Class diagram to describe attributes' and classes' behaviour implied in distance calculation and interaction between them (DistanceSubway, ValueDistFunction & InterfacePartialValueFunction) and ID_GetDistance : Sequence diagram that allows to obtain a distance value between the flat and any place of interest.**(prerequisites : correcting conceptual errors in model)**
* Update pictures and contents from Github : Some contents are not updated, for example, pictures of diagrams that didn't exist. **(prerequisites : need the DC_DistanceApartment)**
* Documentation for a future spider-plot to compare 2 apartments chosen by the user according to several criterias. **(no prerequisites)**

=== Itération 3 UML

[IMPORTANT]
====
Deadline : **April the 12nd, ** 2021
This file only explains the distribution of work between the different teams and indicates their realization.
====

==== Stellan WEA & Abla MIKOU

* SM/PO for this iteration.
* Have split the work between the two groups.
* Organized meetings throughout the week to have a better understanding of the project.
* Made sure everybody was on board and respected the deadline.

==== Seif BOUGUERRA & Samy MEGUENI

* Explanation of the Spider-Plot : Creating a Sequence Diagram that explains the interactions between the user, the value function and the GUI. Writing a better version of the spider-plot's documentation provided at iteration two.
Creating a Spider-Plot class diagram that shows how it's possible to compare two apartments according to the values returned from the ValueFunction.
* Repair Stereotypes (not really a real task) : Trying to remove this dialogue box with opening the eclipse project.

==== Maïrame NDIAYE & Ewen MARGUET

* Update GlobalUseCase : integration of the Spider Plot and make changes as mentioned by the prof.
* Update/Modification of the sequence diagramme IDvaluefonction created in the second iteration. 
* API_key : Search through Internet and create a documentation on how to create a key.

=== Itération 4 UML

[IMPORTANT]
====
Deadline : **May the 3rd, ** 2021
This file only explains the distribution of work between the different teams and indicates their realization.
====

==== Samy MEGUENI & Ewen MARGUET

* SM/PO for this iteration.
* Have split the work between the two groups.
* Daily meeting to know where we stand.
* Make sure everybody is on board and respect the deadline.
* We decided to adopt the professor's suggestions.

==== Abla MIKOU & Seif BOUGUERRA

* Create DistanceValueFunction which will replace ValueDistFunction : for this, we modify `DC Global Detailed`, `DC Global Simplified`, `DC Package ValueFunction` and the documentation.
* Document changes the implementation of DistanceValueFunction in the ApartmentValueFunction will make.

* The french detailed version is listed below :
 ** Créer DistanceValueFunction, qui remplacera ValueDistFunction, qui actuellement ne rend pas du tout le service qu’elle est censée rendre.
 *** Doc visée : principalement un diagramme de classe et qqs ajouts textuels ou graphiques (voir ci-dessous).
 *** À l’initialisation, la classe reçoit un ensemble de LatLng représentant les lieux d’intérêts d’un utilisateur et éventuellement une PVF<Double> qui donne la valeur de l’utilisateur d’un temps de trajet exprimé en secondes.
 *** Par défaut, la PVF est la fonction linéaire par morceau utilisée actuellement dans ValueDistFunction.
 *** getSubjectiveValue(LatLng) reçoit la localisation d’un appartement et renvoie la valeur moyenne de la distance en secondes de l’appartement à un lieu d’intérêt (valeurs calculées grâce à la PVF).
 *** Documenter (textuellement + graphiquement avec un plot de la fonction) le rôle et le fonctionnement de la PVF.
 ** Documenter les changements à effectuer pour pouvoir ajouter une DistanceValueFunction (donc un nouveau critère) dans AVF.
 *** Qu’est-ce que ça change en général dans le logiciel ? Revoir toute la doc et indiquer les changements à prévoir à chaque endroit. Par exemple, il est actuellement possible (à vérifier) de sauvegarder les AVFs ; quel sera l’impact de l’ajout de ce critère sur cet aspect ?
 *** S’inspirer du début d’implémentation proposée dans la link:https://github.com/oliviercailloux-org/projet-apartments/pull/23[PR #23] : quels tests unitaires échouent suite à cet ajout, pourquoi, comment résoudre ces problèmes ?

==== Maïrame NDIAYE & Stellan WEA

* Class diagram for SpiderPlot in order to show its interactions with ohter packages.
* Class diagram of SpiderPlot to display its internal functionning.
* Update the `SD_ValueFunction` diagram taking into account the professor's comments. It will allow the user to understand how he modifies the sorted list of apartments by answering new questions. link:https://github.com/oliviercailloux-org/projet-apartments/pull/19[(PR #19)]

* The french detailed version is listed below :
 ** Diagramme de classe montrant la place de SpiderPlot dans l’architecture et son interaction avec d’autres packages, mettant à jour les diagrammes existants.
 ** Diagramme de la classe SpiderPlot détaillé, et éventuellement d’autres classes liées, montrant son fonctionnement interne et ce qu’il permet ; en vue d’une implémentation en Java.

All of these tasks are related to the 2nd iteration of java : link:https://github.com/oliviercailloux-org/projet-apartments/pull/27[PR #27]

=== Itération 5 UML

[IMPORTANT]
====
Deadline : **May the 31rd, ** 2021.
This file only explains the distribution of work between the different teams and indicates their realisation.
====

==== Seif BOUGUERRA & Stellan WEA

* SM/PO for this iteration.
* Split the work between the two groups.
* Organise meetings throughout the week to have a better understanding of the project.
* Made sure everybody is on board and respected the deadline.

==== Abla MIKOU & Samy MEGUENI

* Update of the Papyrus Model Explorer in Eclipse in order to withdraw the redundancy in `ApartmentValueFunction`.
* Update of future ideas section (mainly withdraw all tasks that we have done and add the future tasks).
* Improvement of the UML sequence diagram about the Spider Plot functioning and its interactions with the user (link:https://github.com/oliviercailloux-org/projet-apartments/pull/21[PR #21]).
* Additional : order all diagrams by topics instead of being classified according to their diagram type (link:https://github.com/oliviercailloux-org/projet-apartments/pull/27[PR #31]). This task is provided to the realisation of the first task.


==== Maïrame NDIAYE & Ewen MARGUET

* Continue the implementation of the `Plot` package class diagram and the integration of `SpiderPlot` class in the global class diagrams while taking consideration of the previous professor notes and resolving the merge conflict according to the link:https://github.com/oliviercailloux-org/projet-apartments/pull/34[PR #34].
* Integration of the `Plot` package in the `diagram-package-global`. This task is provided to the realisation of the first task.
* Beginning of a creation of a clear documentation that will fully explain the project in order to make easier the projet comprehension next year.

== Iterations Java 2021

==== Iteration 1 Java 

[IMPORTANT]
====
Deadline : **April the 18th,** 2021.
This file only explains the distribution of work between the different teams and indicates their realization.
==== 


==== Stellan WEA & Ewen MARGUET

* SM/PO for this iteration.
* Split the work between the two groups.
* Organize meetings throughout the week to have a better understanding of the project.
* Made sure everybody is on board and respected the deadline.

==== Seif BOUGUERRA & Samy MEGUENI
 
Spider-plot

* Implement the new package named `Plot` with its first class named `SpiderPlot` that is able to generate a spider-plot and to display it to the tenant.

==== Maïrame NDIAYE & Abla MIKOU

* Modify the `ValueDistFunction` class : this value function must be based on the apartments' features instead of the tenant's interested places.
* Add the distance as a criteria and integrate it in the calculation of the apartement value function. **(prerequisites : Modify `ValueDistFunction` class)**


==== Iteration 2 Java 

[IMPORTANT]
====
Deadline : **May the 9th,** 2021.
This file only explains the distribution of work between the different teams and indicates their realization.
==== 


==== Maïrame NDIAYE & Seifeddine BOUGUERRA

* SM/PO for this iteration.
* Split the work between the two groups.
* Daily meetings to know where we stand.
* Make sure everybody is on board and respect the deadline.

==== Ewen MARGUET & Abla MIKOU

* Reduce the redundancies in the `AVF` class to simplify the code : Regroup the setters and getters in generic methods. 
* Create `DistanceValueFunction` that replace `ValueDistFunction` and implements the interface `PartialValueFunction<LatLng>` according to the UML implementation at iteration 4.**(prerequisites : Reduce the redundancies)**
* Try to integrate the distance criteria in the `AVF` class according to the documentation done in the iteration 4 of UML. **(prerequisites : Create `DistanceValueFunction`)**

==== Stellan WEA & Samy MEGUENI

* Improving the `SpiderPlot` code by following professor's advices : formating, test, fail fast, static factory methods, and the other trails of improvement as requested in the link:https://github.com/oliviercailloux-org/projet-apartments/pull/22[PR #22]. And taking existing data from apartments of the project instead of generating them by hand still linked to the same PR. 
* Generating image instead of displaying the plot with a swing panel. Display the result will be in a future iteration. **(prerequisites : Improving the SpiderPlot code)**

All of these tasks are related to the 4th iteration of UML : link:https://github.com/oliviercailloux-org/projet-apartments/pull/28[PR #28]


==== Iteration 3 Java

[IMPORTANT]
====
Deadline : **June the 6th, ** 2021
This file only explains the distribution of work between the different teams and indicates their realization.
====


==== Abla MIKOU & Samy MEGUENI

* SM/PO for this iteration.
* Split the work between the two groups.
* Organize meetings throughout the week to have a better understanding of the project.
* Made sure everybody is on board and respected the deadline.

==== Seif BOUGUERRA & Stellan WEA

* Generate statistics : by creating a new class `ApartmentStatistics` that generates statistics for a specified criterion. 
To do this, we will use the link:https://docs.oracle.com/javase/8/docs/api/java/util/DoubleSummaryStatistics.html[DoubleSummaryStatistics].
**Prerequisite : Formatting in Google style.**
* Create a new class in the package `Plot` to generate other types of plot in addition of the statistics. We will use again the link:https://www.jfree.org/jfreechart/[JFreeChart] library.
**Prerequisite : Formatting in Google style.**

It's one of the future idea suggested as : "Generate graphs and statistics of available apartments (average surface, median, number of apartments per surface, …)" in
link:https://github.com/oliviercailloux-org/projet-apartments/blob/master/Doc/idea.adoc[Idea].

==== Maïrame NDIAYE & Ewen MARGUET

* Reformatting code in link:https://google.github.io/styleguide/[Google Style], referring to your future suggestion in link:https://github.com/oliviercailloux-org/projet-apartments/pull/31[PR #31].
* Continue the implementation of the `SpiderPlot` class according to the professor's advice on this link:https://github.com/oliviercailloux-org/projet-apartments/pull/36[PR #36].
**Prerequisite : Formatting in Google style.**
* Add the button "Compare" on `LayoutApartmentGUI` to compare 2 apartments by generating the spider plot. 
**Prerequisite : Formatting in Google style.**

The main purpose of this iteration is to make functional the spider plot. 

==== Iteration 4 Java

[IMPORTANT]
====
Deadline : **June the 27th, ** 2021
This file only explains the distribution of work between the different teams and indicates their realization.
====


==== Maïrame NDIAYE & Seifeddine BOUGUERRA

* SM/PO for this iteration.
* Split the work between the two groups.
* Organize meetings throughout the week to have a better understanding of the project.
* Made sure everybody is on board and respected the deadline.

==== Abla MIKOU & Ewen MARGUET

* Modify the `ApartmentValueFunction` and `LinearAVF` by taking into account the documentation done in the UML Iteration 6 about the comparison of this classes. 
* Integrate `AskOpinionForUtility` in the application. In fact, this class has been implemented but it is still disconnected from the rest of the application while 
it is necessary to recover the answers of the Tenant to have the subjective values of the apartments. Thus, this will allow us to display correctly the list taking 
into account the calculations made by the application. *Prerequisite : It's necessary to do the first task to did this*. 
* Continue the integration of the criterion distance in the `ValueFunction` (*Prerequisite : It's necessary to do the first task to did this*) : 
** Correct the `DistanceValueFunction` according to the teacher's advices at link:https://github.com/oliviercailloux-org/projet-apartments/pull/35[PR #35].
** Continue the link:https://github.com/oliviercailloux-org/projet-apartments/pull/37[PR #37] by taking care teacher's recommendations. 

==== Stellan WEA & Samy MEGUENI

* Continue the creation of the class `Histograms` in the package `Plot` to generate other types of plot according to the professor's advice on this link:https://github.com/oliviercailloux-org/projet-apartments/pull/49[PR #49].
* Continue the creation of the class `ApartmentStatistics` in the package `Apartment` to generate statistics about the apartment according to the professor's advice on this link:https://github.com/oliviercailloux-org/projet-apartments/pull/48[PR #48].
* Continue the implementation of the `SpiderPlot` by taking into account the professor's recommendations during the last iteration : https://github.com/oliviercailloux-org/projet-apartments/pull/51[PR #51] and https://github.com/oliviercailloux-org/projet-apartments/pull/50[PR #50] : 
 ** Improve the `SpiderPlot` class code.
 ** Complete the integration of the `SpiderPlot` button in the `LayoutApartmentGUI` class.

The project documentation is link:Doc/README.adoc[here].

The code is hereby published under the MIT License, with the permission of the contributors.
